#include "Drive.h"

#include "../RobotMap.h"



#include "../Commands/TankDrive.h"



Drive::Drive() : Subsystem("Drive")
{

	m_right_encoder = RobotMap::driveTraindBaseEncoderR;
	m_left_encoder = RobotMap::driveTraindBaseEncoderL;
    dBaseL1 = RobotMap::driveTraindBaseL1;
    dBaseL2 = RobotMap::driveTraindBaseL2;
    dBaseL3 = RobotMap::driveTraindBaseL3;
    dBaseR1 = RobotMap::driveTraindBaseR1;
    dBaseR2 = RobotMap::driveTraindBaseR2;
    dBaseR3 = RobotMap::driveTraindBaseR3;
    m_gyro = RobotMap::driveTraindBaseGyro;
    // You should probably add gyro for course correction, but I am going to be mega lazy and just use the encoders
    // If we were only using one encoder, you would be forced to use the gyro, but thanks for allowing my laziness!
    //dBaseGyro = RobotMap::driveTraindBaseGyro;



    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

	// Initialize the robot drive. The constructor is documented at

	// http://first.wpi.edu/FRC/roborio/release/docs/cpp/classRobotDrive.html#a47180c144fcca9e7550f7cb906c8b79a

	drive = new RobotDrive(

		    dBaseL1,

		    dBaseL2,


		    dBaseR1,

		    dBaseR2

	);




	drive->SetSafetyEnabled(false);

}



void Drive::InitDefaultCommand() {

    // Set the default command for a subsystem here.

    // SetDefaultCommand(new MySpecialCommand());



        SetDefaultCommand(new TankDrive());

}



void Drive::MyDrive(float left, float right)

{

	drive->TankDrive(left, right);

}



void Drive::MyDrive(Joystick * leftStick, Joystick * rightStick)

{

	drive->TankDrive(leftStick->GetY(),rightStick->GetY());

}

int Drive::GetRightEncoder()
{
	return m_right_encoder->Get();
}

int Drive::GetLeftEncoder()
{
	return m_left_encoder->Get();
}

float Drive::GetYaw()
{
	return m_gyro->GetAngle();
}

void Drive::ResetEncoders()
{
	m_left_encoder->Reset();
	m_right_encoder->Reset();
}

void Drive::CalibrateGyro()
{
	m_gyro->Calibrate();
}


void Drive::Stop()
{
	drive->TankDrive(0., 0.);
}



// Put methods for controlling this subsystem

// here. Call these from Commands.
