// RobotBuilder Version: 2.0

//

// This file was generated by RobotBuilder. It contains sections of

// code that are automatically generated and assigned by robotbuilder.

// These sections will be updated in the future when you export to

// C++ from RobotBuilder. Do not put any code or make any change in

// the blocks indicating autogenerated code or it will be lost on an

// update. Deleting the comments indicating the section will prevent

// it from being updated in the future.





#ifndef DRIVE_H

#define DRIVE_H

#include "Commands/Subsystem.h"

#include "WPILib.h"

#include "CANTalon.h"

/**

 * This class encapsulates the drivebase subsystem and implements the command calling methods to

 * drive the robot.

 */

class Drive: public Subsystem {

private:

	// It's desirable that everything possible is private except

	// for methods that implement subsystem capabilities



	/*
	 * The left front motor of the drive base
	 */
	std::shared_ptr<CANTalon> dBaseL1;

	/*
	 * The left back motor of the drive base
	 */
	std::shared_ptr<CANTalon> dBaseL2;

	/*
	 * The right front motor of the drive base
	 */
	std::shared_ptr<CANTalon> dBaseR1;

	/*
	 * The right back motor of the drive base
	 */
	std::shared_ptr<CANTalon> dBaseR2;

	std::shared_ptr<Encoder> m_right_encoder;

	std::shared_ptr<Encoder> m_left_encoder;


	std::shared_ptr<ADXRS450_Gyro> m_gyro;
	/*

	 * This is the physical pointer that will run the robot drive.

	 */

	RobotDrive * drive;

public:

	/**
	 * The number of encoder ticks per rotation
	 */
	const int TICKS_PER_ROTATION = 256;

	/**
	 * The size of your wheels (in inches)
	 */
	const float WHEEL_DIAMETER = 3.5;

	/**
	 * This is the width of your robot (in inches)
	 */
	const float BASE_WIDTH = 26;


	/*

	 * Initializes a new instance of the Drive subsystem class.

	 */

	Drive();



	/*

	 * Initializes the default command for driving this robot around (TankDrive).

	 */

	void InitDefaultCommand();



	/*

	 * This method will drive the robot with the raw speeds provided

	 *

	 * @param left: The amount of power provided to the left motor

	 * @param right: The amount of power provided to the right motor

	 */

	void MyDrive(float, float);



	/*

	 * This method will drive the robot given two joysticks. Note that this will take the

	 * Y axis of th ejoysticks provided!

	 *

	 * @param leftStick: The left joystick to use

	 * @param rightJoystick: The right joystick to use

	 */

	void MyDrive(Joystick *, Joystick *);

	/**
	 * Stops the robot
	 */
	void Stop();

	/*
	 * Gets the current right encoder value in ticks.
	 */
	int GetRightEncoder();

	/*
	 * Gets the current left encoder value in ticks.
	 */
	int GetLeftEncoder();

	/*
	 * Gets the current angle measured by the gyro.
	 */
	float GetYaw();

	/*
	 * Use this method to zero the encoders on the Robot.  ONLY USE WHEN YOU'RE SURE THE ROBOT IS AT REST!
	 */
	void ResetEncoders();

	/*
	 * Use this method to calibrate the gyro on the Robot.  ONLY USE WHEN YOU'RE SURE THE ROBOT IS AT REST!
	 */
	void CalibrateGyro();

};



#endif
