// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.




#include "Feeder.h"
#include "../RobotMap.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

Feeder::Feeder() : Subsystem("Feeder") {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    feederWheel = RobotMap::feederfeederWheel;
    feederWheel2 = RobotMap::feederfeederWheel2;


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
}

void Feeder::InitDefaultCommand() {
    // Set the default command for a subsystem here.
    // SetDefaultCommand(new MySpecialCommand());
}

void Feeder::FeedBall(){
	feederWheel->Set(.75);
	feederWheel2->Set(.75);
}

void Feeder::ReturnBall(){
	feederWheel->Set(-.75);
	feederWheel2->Set(-.75);
}

void Feeder::Off(){
	feederWheel->Set(.0);
	feederWheel2->Set(.0);
}


// Put methods for controlling this subsystem
// here. Call these from Commands.

