// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef GEARER_H
#define GEARER_H
#include "Commands/Subsystem.h"
#include "WPILib.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class Gearer: public Subsystem {
private:
	// It's desirable that everything possible is private except
	// for methods that implement subsystem capabilities
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	std::shared_ptr<DigitalInput> gearDetect;
	std::shared_ptr<SpeedController> gearRoller;
	std::shared_ptr<DoubleSolenoid> gearSolenoid1;
	//std::shared_ptr<DoubleSolenoid> gearSolenoid2;
	std::shared_ptr<DoubleSolenoid> gearSecurer;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
public:
	Gearer();
	void InitDefaultCommand();

	//Extends gearer to the ground
	void Extend();

	//retracts gearer to up position
	void Retract();

	// turns off the system
	void Off();

	//runs motor to collect gear
	void In();

	//Expels gear from gearer
	void Out();

	// These are all methods for components that don't exist yet
	//checks for gear
	//bool GetHasGear() const;

	//secures gear with piston
	void Secure();

	//releases gear from securing piston
	void UnSecure();
};

#endif
