// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "AutonomousCommand.h"
#include "TankDrive.h"
#include "MoveGearer.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

AutonomousCommand::AutonomousCommand() {
        // Use requires() here to declare subsystem dependencies
    // eg. requires(Robot::chassis.get());
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	AddSequential(new TankDrive(-.7), 0.9);
	printf("0. Moved backwards slowly \n");
	AddSequential(new TankDrive(0), .5);
	printf("5. Stopped \n");
	AddParallel(new MoveGearer(true), 3);
	printf("10. Gearer activated \n");
	AddSequential(new TankDrive(.5), 1);
	printf("15. Moved forward while moving the gear! \n");
	AddSequential(new TankDrive(0), 2);
	printf("20. Stopped! \n");
	AddSequential(new TankDrive(-.5), 1);
	printf("25. B-line slowly \n");
	AddSequential(new TankDrive(0), 2);
	printf("30. Stopped! \n");

	printf("Congratulations, You've Completed the Dungeon ");
}
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

