// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef ROBOTMAP_H
#define ROBOTMAP_H

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "WPILib.h"

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
class RobotMap {
public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	static std::shared_ptr<Encoder> driveTraindBaseEncoderL;
	static std::shared_ptr<Encoder> driveTraindBaseEncoderR;
	static std::shared_ptr<SpeedController> driveTraindBaseL1;
	static std::shared_ptr<SpeedController> driveTraindBaseL2;
	static std::shared_ptr<SpeedController> driveTraindBaseL3;
	static std::shared_ptr<SpeedController> driveTraindBaseR1;
	static std::shared_ptr<SpeedController> driveTraindBaseR2;
	static std::shared_ptr<SpeedController> driveTraindBaseR3;
	static std::shared_ptr<AnalogGyro> driveTraindBaseGyro;
	static std::shared_ptr<DigitalInput> gearergearDetect;
	static std::shared_ptr<SpeedController> gearergearRoller;
	static std::shared_ptr<DoubleSolenoid> gearergearSolenoid1;
	static std::shared_ptr<DoubleSolenoid> gearergearSolenoid2;
	static std::shared_ptr<SpeedController> ballCollectorintakeRoller;
	static std::shared_ptr<DoubleSolenoid> ballCollectorcollectorSolenoid1;
	static std::shared_ptr<DoubleSolenoid> ballCollectorcollectorSolenoid2;
	static std::shared_ptr<SpeedController> magiKarpetbeltMotor;
	static std::shared_ptr<SpeedController> feederfeederWheelLow;
	static std::shared_ptr<SpeedController> feederfeederWheelHigh;
	static std::shared_ptr<SpeedController> shootershooterWheelPrimary;
	static std::shared_ptr<SpeedController> shootershooterWheelBooster;
	static std::shared_ptr<Encoder> shootershooterEncoderPrimary;
	static std::shared_ptr<Encoder> shootershooterEncoderBooster;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

	static void init();
};
#endif
