// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef ROBOTMAP_H
#define ROBOTMAP_H

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "WPILib.h"

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */

// drive base sensors
const int CHANNEL_A_LEFT_BASE_ENCODER = 0;
const int CHANNEL_B_LEFT_BASE_ENCODER = 1;
const int CHANNEL_A_RIGHT_BASE_ENCODER = 2;
const int CHANNEL_B_RIGHT_BASE_ENCODER = 3;
const int DRIVE_GYRO = 4;

// drive base speed controllers
const int DRIVE_SPEED_LEFT_1 = 0;
const int DRIVE_SPEED_LEFT_2 = 1;
const int DRIVE_SPEED_LEFT_3 = 2;
const int DRIVE_SPEED_RIGHT_1 = 3;
const int DRIVE_SPEED_RIGHT_2 = 4;
const int DRIVE_SPEED_RIGHT_3 = 5;

// gearer stuff
const int GEAR_DETECTOR = 0;
const int GEAR_ROLLER = 1;
const int GEAR_SOLENOID_1_FORWARD_CHANNEL= 2;
const int GEAR_SOLENOID_1_REVERSE_CHANNEL = 3;
const int GEAR_SOLENOID_2_FORWARD_CHANNEL = 4;
const int GEAR_SOLENOID_2_REVERSE_CHANNEL = 5;

//ball collecter stuff
const int INTAKE_ROLLER = 0;
const int COLLECTOR_SOLENOID_1_FORWARD_CHANNEL = 1;
const int COLLECTOR_SOLENOID_1_REVERSE_CHANNEL = 2;
const int COLLECTOR_SOLENOID_2_FORWARD_CHANNEL = 3;
const int COLLECTOR_SOLENOID_2_REVERSE_CHANNEL = 4;

// magikarpet
const int MAGIKARPET_BELT_MOTOR = 8;

// feeder
const int F_WHEEL_LOW = 9;
const int F_WHEEL_HIGH = 10;

// shooter
const int S_WHEEL_PRIMARY = 11;
const int S_WHEEL_BOOSTER = 12;
const int S_ENCODER_A_PRIMARY = 5;
const int S_ENCODER_B_PRIMARY = 6;
const int S_ENCODER_A_BOOSTER = 7;
const int S_ENCODER_B_BOOSTER = 8;


//Intake Roller Current Limit
const double INTAKE_ROLLER_CURRENT_LIMIT = 1.0;

class RobotMap {
public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	static std::shared_ptr<Encoder> driveTraindBaseEncoderL;
	static std::shared_ptr<Encoder> driveTraindBaseEncoderR;

	static std::shared_ptr<SpeedController> driveTraindBaseL;
	static std::shared_ptr<SpeedController> driveTraindBaseR;

	static std::shared_ptr<AnalogGyro> driveTraindBaseGyro;
	static std::shared_ptr<DigitalInput> gearergearDetect;
	static std::shared_ptr<SpeedController> gearergearRoller;
	static std::shared_ptr<DoubleSolenoid> gearergearSolenoid1;
	static std::shared_ptr<DoubleSolenoid> gearergearSolenoid2;
	static std::shared_ptr<SpeedController> ballCollectorintakeRoller;
	static std::shared_ptr<DoubleSolenoid> ballCollectorcollectorSolenoid1;
	static std::shared_ptr<DoubleSolenoid> ballCollectorcollectorSolenoid2;
	static std::shared_ptr<SpeedController> magiKarpetbeltMotor;
	static std::shared_ptr<SpeedController> feederfeederWheel;
	static std::shared_ptr<SpeedController> shootershooterWheelPrimary;
	static std::shared_ptr<SpeedController> shootershooterWheelBooster;
	static std::shared_ptr<Encoder> shootershooterEncoderPrimary;
	static std::shared_ptr<Encoder> shootershooterEncoderBooster;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

	static void init();
};
#endif
